### ISSUE TITLE
Ember 4.0

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/rfcs#582]
Let us set up a timeline for Ember 4.0 in order to be able to drop support for IE11.

**Comment by Gaurav0** [comment]
For reference: https://blog.emberjs.com/2017/10/03/the-road-to-ember-3-0.html

**Comment by NullVoxPopuli** [comment]
Things I would like to see landed before Ember 4:
 - embroider 
  + tree shaking
 - option to have no controllers
 - typed templates
 - template imports
   + ability to have components anywhere
   + file/project linter to enforce component locations.
- binary templates
- information on GlimmerVM as WASM (was this a good idea?)

All of this might be too far out there, but also, It could warrant another edition. 

If Ember 3 is carrying too much bloat with it, I'd be cool with a bump  to 4. However, because everyone is really slow at upgrading, I think we'd want to wait at least a couple of LTSs.. Maybe once 3.24 is LTS, it'd make sense to do Ember 4.0, and remove all the cruft from the pre-octane era

**Comment by Gaurav0** [comment]
Why should we continue to support IE11 for another year or two while all that is being done?

**Comment by NullVoxPopuli** [comment]
tbf, IE11 is holding everyone back that needs to support it.

**Comment by lifeart** [comment]
IE 11 supporting may be opt-in feature with some codestyle limitations.

**Comment by makepanic** [comment]
As an alternative to dropping IE11 one could also investigate what other frameworks are doing with [Differential Loading](https://angular.io/guide/deployment#differential-loading) that splits the build output into a evergreen and legacy bundle.

This allows newer browser to get a small payload while older browsers can still work by loading more javascript.

There's also the possibility of letting the developer handle old browsers themselves by making polyfills easaier to load, see e.g. [polyfills.ts in NG2](https://angular.io/guide/browser-support#mandatory-polyfills).

This won't work if ember uses API that isn't possible to polyfill though.

**Comment by Panman82** [comment]
I might be wrong here, but I think there are newer things that cannot be polyfilled and therefore (once used) will forever break backwards compatibility with IE11.

**Comment by pzuraq** [comment]
Certain features, such as native Proxy, are impossible to polyfill, and so the framework cannot use them for many production features. I think the ability to use Proxy would be incredibly helpful, and definitely should factor into the timeline.

I do think we should consider adding the Babel polyfill by default prior to dropping support for IE11, specifically so libraries and Ember can begin to adopt some feature now and smooth out the transition. The number one feature I can think of is native Symbol, which is the future for how custom iterables will work in Ember in the future (and would allow us to deprecate certain obscure behaviors of `{{each}}` and EmberArray/ArrayProxy).

Overall, I’m in favor of a faster timeline, especially now that Edgium has been released with IE11 compat mode.

**Comment by chriskrycho** [comment]
@NullVoxPopuli 

> Things I would like to see landed before Ember 4: …

This is actually pretty much the opposite of how we've learned to approach majors in Ember—that is, in *dropping* deprecated functionality. Nearly every one of those could land on any old minor version, and few of them besides controllers even have any relationship to removal of deprecated code. (And controllers aren't yet deprecated!)

Dropping IE11 support (as well as trimming a *lot* of defunct code elsewhere) is a high-value reason to bump to 4.0. Nothing says we can't do a 5.0 a year or 18 months later (or six months, for that matter, depending on how things shake out!). And we'll just keep incrementally delivering features along the way.

**Comment by NullVoxPopuli** [comment]
Cool. I was under the impression we were staying on 3 for as long as IE11 exists. :)

**Comment by chriskrycho** [comment]
IE11 will *exist* until Windows 10 is dead (which is a *long* time from now); IE11 will not be *recommended* or *supported* by Microsoft in that timeline, however; the Edge-on-Chromium replacement includes an IE11 compatibility mode to allow enterprise organizations which have IE11-only intranets and other internal software which *requires* and *only* runs on IE11 to work in Edge, which they've back-ported to Windows 7. (This is what @pzuraq was referring to above with his comment about "Edgium… with IE11 compact mode".)

Most likely, Ember can therefore safely drop it at some point later this year (or at latest in early 2021, I'd guess). The specifics will depend on how major ecosystem players' needs shake out, and what timeline Microsoft pushes for, but IE11 support *can* go away some point sooner rather than later. 😅

**Comment by NullVoxPopuli** [comment]
> Most likely, Ember can therefore safely drop it at some point later this year (or at latest in early 2021, I'd guess). 

This is wonderful news.


Then yes, I'm a on board with the aggressive major version bumps to clean up deprecations. :)

**Comment by NullVoxPopuli** [comment]
Oof. I'm a potato today. 

Just realized the deprecation of IE11 has absolutely nothing to do with the other deprecations and the eventual version 4

**Comment by gossi** [comment]
What I like for ember in majors it is dropping deprecated APIs and in following semver is able to adjust the supported environments (eg. node and browsers) - am I right? Then this information is missing for me:

The list of dropped APIs:
- https://deprecations.emberjs.com/v3.x

-> Is this list "enough"? In terms of whether one or another API should be deprecated before in order to ... ? In order to achieve _something_ or prepare ember4 to be capable of ... ?

The newly supported browsers:
- ???

Node
- ???

IE11: Personally I'm super happy to drop it as it suggests slimmer builds. On the other hand at work we have to support IE11. Even though MS emulates older browsers in their newer ones, that does not necessarily mean intranets or their IT landscape will update to them. For those environments IE11 is often strongly coupled to it. Just want to raise awareness for this and definitely not advocating to keep IE11 support. Maybe ember3 will become the IE11 version and ember4 the modern version. The thing I'm worried about then is to new changes aren't available consumers that are stuck with supporting IE11 and whether this is creating a gap within the ecosystem of addons, etc.

Don't click this link: https://death-to-ie11.com/

**Comment by Gaurav0** [comment]
@gossi For how long does your company need to support IE11?

**Comment by mehulkar** [comment]
I think Ember 4.0 should also drop `Ember.Component`, so there would need to be an RFC to deprecate that first

**Comment by pzuraq** [comment]
I don't think it's likely that we'll be able to drop `Ember.Component` in that timeline. We should start with an optional feature flag IMO, and enable it by default in v4.0 (or sooner if possible) so that new apps aren't paying the cost for it.

**Comment by lifeart** [comment]
How support IE11 in Angular -> https://medium.com/javascript-in-plain-english/angular-how-to-support-ie11-d3b8c3d3494e

**Comment by btecu** [comment]
**Ember.js 4** without the option to opt-in to support IE 11 is not a good idea. It will cause **Ember.js** to lose market share because many companies unfortunately still have to support IE11.

**Comment by Gaurav0** [comment]
@btecu I don't really believe that. Most corporations and governments that require users to use IE11 do not lock down users to it now; they permit users to use modern browsers as well. In my experience almost all computers have a modern browser installed in addition to IE11 because so many sites no longer work in IE11 around the web. The question really is how long we need to support it. It may be that we need to for as long as another year, but I don't think we should have to support it forever.

**Comment by ondrejsevcik** [comment]
I also believe that it's not worth it. The IE11 share is around 1%. The number of companies supporting IE11 and upgrading to Ember 4.0 will be also very low (my guess). And ultimately Ember devs will have to pay for it -> bundle size, core dev's time that could be spent on something else, writing documentation, bugfixes...

**Comment by pzuraq** [comment]
I think the thing to watch will be how the new Edge affects that number. My understanding is that it's IE11 compat mode is not an emulation - it quite literally includes the actual IE11 engine (which is frozen anyways), and uses it to render IE11 only pages in an opt-in basis.

If Microsoft begins pushing major companies to adopt, we may see IE11 usage drop significantly in the next year or so, and smaller companies may begin adopting as well. Those would be good indicators about when to make this change.

**Comment by gossi** [comment]
@Gaurav0 
> I don't really believe that. Most corporations and governments that require users to use IE11 do not lock down users to it now; they permit users to use modern browsers as well. In my experience almost all computers have a modern browser installed in addition to IE11 because so many sites no longer work in IE11 around the web.

This is not the problem, those people I hope are pretty happy to use modern browsers and do so. The problem are such IT system, that provide you a terminal session onto it with a preconfigured system that you can NOT change (as a user). This is where IE11 is pre-installed and unchangeable. I also don't see Edge as a replacement there (I'd consider Edge a modern browser) as these systems are really static for a long time. Most of the time bank or public/governance administration systems.

What might be a way forward, is to strip out ie11 required code into an `@ember/ie11-compat` package (similar to `@ember/jquery`). That would be in the end not much differen than removing `ie11` in your targets file. Second is, I don't really know how interchangeable the ember internals code is, to "just" move that compatibility layer into an external package. This would require the internals architecture to change to support those hooks. I guess after all the benefits are very small and don't outweigh the effort for it. Take it with a grain of salt, it's very assumptive statement - corrections are welcome.
Even if stripping this out, it is still stricting ember to a given feature set (e.g. no proxies 😞). To sad to continue writing now :D

**Comment by Gaurav0** [comment]
> This is not the problem, those people I hope are pretty happy to use modern browsers and do so. The problem are such IT system, that provide you a terminal session onto it with a preconfigured system that you can NOT change (as a user). This is where IE11 is pre-installed and unchangeable. I also don't see Edge as a replacement there (I'd consider Edge a modern browser) as these systems are really static for a long time. Most of the time bank or public/governance administration systems.

Some of those systems are still running Windows 2007 with IE8 lol. It didn't mean we couldn't drop support. If you are writing an application for such a machine, you can stick with the last version of Ember 3.x indefinitely. Heck, there are some people still using Ember 1.13.

As to creating a compatibility layer, if we ever want to use some features like proxies in Ember, we simply can't create such a layer. Those features cannot be polyfilled.

I can accept that we can't get off IE11 today. I can't accept that we never can. With market share so low, the vast majority of us can already ignore IE11. Much of the web is already incompatible with it. I think we need to talk timelines now to prepare users of Ember to let their customers know they will stop supporting it. 3 months would be 3.18. 9 months is 3.22. 15 months is 3.26. Let's pick one and let people plan.

**Comment by Panman82** [comment]
> What might be a way forward, is to strip out ie11 required code into an `@ember/ie11-compat` package (similar to `@ember/jquery`). That would be in the end not much differen than removing `ie11` in your targets file. Second is, I don't really know how interchangeable the ember internals code is, to "just" move that compatibility layer into an external package. This would require the internals architecture to change to support those hooks.

@gossi See the comment above: https://github.com/emberjs/rfcs/issues/582#issuecomment-577293006

So I understand maintaining back compat, but at what point does the framework _need_ to push forward to stay relevant?? I just can't get over that 1% is going to hold back _all_ other users from improvements...

**Comment by jelhan** [comment]
> Ember.js 4 without the option to opt-in to support IE 11 is not a good idea. It will cause Ember.js to lose market share because many companies unfortunately still have to support IE11.

I'm not sure if that statement is right. I'm working on an application suite for the industrial sector. For a long term IE11 support couldn't be questioned. It was used by many internal employees as well as many customers. Some even haven't had the option to install another browser and were forced to use IE11.

This has changed dramatically in the last half a year. The changing point was Windows 7 to Windows 10 migration. Nearly all employees have a modern browser preinstalled now. There was an official announcement to all internal employees that IE11 must not be used for day-to-day activities due to security reasons. We heard similar stories from our customers.

We haven't yet made a final decision to drop IE11 support but it's very likely that we will have that decision soon. Half a year ago no one of us had imagined that this will be possible in such a short period of time.

**Comment by lvegerano** [comment]
> I don't think it's likely that we'll be able to drop Ember.Component in that timeline. We should start with an optional feature flag IMO, and enable it by default in v4.0 (or sooner if possible) so that new apps aren't paying the cost for it.

A lot of devs won't make the change until they have to. The band-aid will be ripped at some point and devs will complain whether is Ember 4/5. I just don't see benefits of prolonging support of the old Ember programing model.

**Comment by Gaurav0** [comment]
> A lot of devs won't make the change until they have to. The band-aid will have to be ripped at some point and devs will complain, whether is Ember 4/5. I just don't see benefits of prolonging support of the old Ember programing model.

I've worked at an enterprise company that couldn't upgrade Ember to 2.0 because of the radical last minute deprecations and removals. It left such a bad taste that they ended up migrating away from Ember instead. I'm determined that we don't make that mistake again.

Large applications have thousands of `@ember/component`s and will not be able to migrate them all quickly. There isn't ever going to be a codemod for this. They need an escape hatch.

I'm all for moving `@ember/component` to an optional feature or addon, but we should not deprecate it for at least one whole year, probably two, and likely target Ember 5.0 when we do.

**Comment by lvegerano** [comment]
We'll have to agree to disagree.
> I've worked at an enterprise company that couldn't upgrade Ember to 2.0 

Ember 1 to 2 is a different beast. Was a much harder upgrade path. In our case we stopped development for 2 weeks. This is key

>because of the radical last minute deprecations and removals

The suggestion is not to make it last minute but announce it now. There's plenty of time, and the upgrade path is set and much clear.

> It left such a bad taste that they ended up migrating away from Ember instead.

Sounds like an emotional decision, not a pragmatic one. EmberJS is an asset and a strength in our dev team, I could've not imagine re-writing our whole app back then (ember 1 - 2) much less now that has tripled in size. We don't have thousand of components but we have enough that I know it will take our team a year if not more to fully migrate. Still there is light at the end of the tunnel and there is no better motivation than getting stuck with old tech. 

> I'm all for moving @ember/component to an optional feature or addon

I guess it may not be that bad. I all depends on the bloat that the core will have to carry to support this.

**Comment by pzuraq** [comment]
I'm pretty familiar with the code for classic components, and I believe we could write an optional feature flag that would remove all of the code for them when they are disabled. I think we could also do this sooner rather than later.

If anyone wants to start working on that RFC, let me know! I can provide guidance 😄

**Comment by mehulkar** [comment]
> If anyone wants to start working on that RFC, let me know

I'll be taking this on in the next 7-10 days for #587. If anyone is interested in beating me to it, message me on Discord or Twitter DM! I'd be happy to help edit early rounds, etc if that would help.

**Comment by sandstrom** [comment]
> I don't really believe that. Most corporations and governments that require users to use IE11 do not lock down users to it now; they permit users to use modern browsers as well. In my experience almost all computers have a modern browser installed in addition to IE11 because so many sites no longer work in IE11 around the web.

I second this. We dropped IE11 support for our Ember enterprise application (~1500 businesses) this autumn. Before doing so we contacted ~10-15 companies that still had people using IE11. 

Every single one of them also had Chrome installed, it turned out. So it was just a bunch of people using IE11 out of habit. There was zero complaints from our customers IT departments due to this change.

Meanwhile, supporting IE11 is a tax on all framework improvements + prevents us from using some new technology. I'd certainly favor dropping IE11 support.

And when doing so, make sure we also skip support for edge-before-chromium. Since Edge is evergreen that shouldn't be a big problem and it would unlock a ton of useful browser technologies that weren't supported in old Edge.

**Comment by Gaurav0** [comment]
Just waiting for a timeline from LinkedIn and Intercom on when they might be able to drop IE11 support, then I will go ahead and write an RFC. Thanks, all.

**Comment by mehulkar** [comment]
Just want to crosslink #383 here as it relates to IE11 support also

**Comment by mehulkar** [comment]
Bootstrap dropped IE11 support: https://github.com/twbs/bootstrap/pull/30377

**Comment by mehulkar** [comment]
Ionic dropping support for IE11: https://twitter.com/maxlynch/status/1252341822413664256

**Comment by mehulkar** [comment]
TIL, IE11 support is tied to Windows 10 support, which ends pretty widely this year. It will only be supported for enterprise customers as paid support until 2025.

https://www.swyx.io/writing/ie11-eol/

**Comment by karthiicksiva** [comment]
LinkedIn is dropping IE11 support from `July 1, 2020`.  @Gaurav0 

https://twitter.com/chadhietala/status/1261047086029701120

https://www.linkedin.com/help/linkedin/answer/4135/supported-internet-browsers-for-linkedin

**Comment by gossi** [comment]
I tried to be neutral above in my comments about ie11. Still neutral: ie11 is blocking evolution here, so it is good to drop.

Personal: People still needing to support ie11 will still be able to use ember3.
Also personally: For private projects I ditched ie11 long time ago 😊 

So, happy to see this moving forward.

**Comment by mehulkar** [comment]
Redwood JS dropping IE 11 support also https://twitter.com/appfactory/status/1305448361902964736?s=21

**Comment by jherdman** [comment]
Precision Nutrition has informally dropped IE11 support, but will do so explicitly once Ember drops support.

**Comment by mehulkar** [comment]
Vue 3 and Preact 11 also dropping IE11 support:

- Vue 3 dropping IE1 support: https://github.com/vuejs/rfcs/pull/294
- Preact 11 also maybe: https://twitter.com/_developit/status/1387804823492440069
- Angular "deprecating support": https://github.com/angular/angular/issues/41840

**Comment by NullVoxPopuli** [comment]
Ember 4 does not support IE11.
With ie11 in `targets`, you'll get this warning:
```
WARNING: Internet Explorer 11 is listed in your compilation targets, but it will no longer be supported in the next major version of Ember. Please update your targets to remove IE 11 and include new targets that are within the updated support policy. For details on the new browser support policy, see:
```
The browser support policy does not include IE11 under Ember 4: https://emberjs.com/browser-support/
And a screenshot, because I'm sure the page will change over time: 
![image](https://user-images.githubusercontent.com/199018/116621504-3e518480-a911-11eb-8b6b-8788a8f6d2b8.png)

**Comment by quantuminformation** [comment]
I've been using Svelte pretty much full time the last 10 months so ie11 has never been on my mind, except for one client who had an old version of edge, and that wasn't ie11.

**Comment by mehulkar** [comment]
Sounds like we can close this isssue then. The title is "Ember 4.0", but seems it became about dropping IE11 at some point. Both are solved issues now

**Comment by jelhan** [comment]
> Sounds like we can close this isssue then. The title is "Ember 4.0", but seems it became about dropping IE11 at some point. Both are solved issues now

I'm not sure if I would consider "Ember 4.0" as solved. I also noticed the alpha release. But I'm still surprised that there was no public announcement of planned roadmap yet.

I expected to see a similar announcement as [The road to 3.0](https://blog.emberjs.com/the-road-to-ember-3-0/). Especially covering the following topics:

- Which version will be the last minor release for v3.x?
- Which version will be the last LTS release for v3.x?
- Which v3.x version will be (or have been?) the last one introducing a new deprecation targeting v4?
- Which v4.x version is the first one targeted for LTS?

Maybe I just missed that announcement. Otherwise a RFC could have been one way to discuss and decide on these topics.

**Comment by pzuraq** [comment]
> But I'm still surprised that there was no public announcement of planned roadmap yet.

It's still not guaranteed that the upcoming release will be 4.0. There's been some instability with the release of 3.27 (which is still ongoing) and we want to make sure all of those issues are figured out before 4.0 is finalized.

> Which version will be the last minor release for v3.x?

I don't think this is something we should/could decide up front. It locks us into a timeline that we may end up missing, like we did with the final release for Ember Octane. More so, the question is "what are the changes that will occur in 4.0, and what are the conditions for its release?". When all of those changes have landed, and conditions fulfilled, then we can release 4.0 at any time, and we would determine that as we were executing. This is more inline with the train release model - if you miss the train, you can always catch the next one.

> Which version will be the last LTS release for v3.x?

As a matter of policy, the last version of 3.x that is released will always become the last LTS for 3.x I believe. It does not need to be a version that would normally be an LTS, it could be any version. The idea being its the last version before the major, so everyone should be able to update to it, address deprecations, and update the major.

> Which v3.x version will be (or have been?) the last one introducing a new deprecation targeting v4?

This is definitely something we could have debated previously, and possibly should debate for upcoming majors. The current consensus is that 3.27 is the last version that will introduce any deprecations for this cycle, FWIW. It originally was going to be 3.26, but a couple of implementations slipped into 3.27 due to complexity (the Ember global especially).

> Which v4.x version is the first one targeted for LTS?

The first version will be 4.4, in accordance with the existing policy/procedures.

**Comment by mehulkar** [comment]
> I'm not sure if I would consider "Ember 4.0" as solved.

My understanding is that the issues in this repo are ideas for RFCs. A 4.0 release is all but guaranteed, and dropping support for IE11 is confirmed. So my thinking is that this issue is no longer an idea for an RFC. The related RFC work is done. A roadmap blog post is out-of-band thing, IMO. 

I don't have a problem with leaving this open though 😄
